### ISSUE TITLE
test

### ISSUE THREAD

**Issue by DouBiBaNi** [DouBiBaNi/DouBiBaNi.github.io#1]
# test

This is a test.

**Comment by goofegg** [comment]
你的主页看起来挺正常的啊，哪里有问题？

**Comment by DouBiBaNi** [comment]
> 你的主页看起来挺正常的啊，哪里有问题？
主要就是右侧menu的js失效了， 底部footer也没有 😰

**Comment by goofegg** [comment]
> > 你的主页看起来挺正常的啊，哪里有问题？
> > 主要就是右侧menu的js失效了， 底部footer也没有 😰

感觉和我的差不多啊，config文件里的页首/下面多了一个空行，不知道是不是这个影响的，你删掉试试

**Comment by DouBiBaNi** [comment]
> > > 你的主页看起来挺正常的啊，哪里有问题？
> > > 主要就是右侧menu的js失效了， 底部footer也没有 😰
> 
> 感觉和我的差不多啊，config文件里的页首/下面多了一个空行，不知道是不是这个影响的，你删掉试试

谢谢你，重新写了一边json就没问题了，可能之前写的时候出了点问题 :blush:
